export const FETCH_CATEGORY_PRODUCTS = 'FETCH_CATEGORY_PRODUCTS'
export const FETCH_CATEGORY_PRODUCTS_SUCCESS = 'FETCH_CATEGORY_PRODUCTS_SUCCESS'
export const FETCH_CATEGORY_PRODUCTS_ERROR = 'FETCH_CATEGORY_PRODUCTS_ERROR'
export const FETCH_CATEGORY_PRODUCTS_RESET = 'FETCH_CATEGORY_PRODUCTS_RESET'

export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';

export const REQUEST_RESET = 'REQUEST_RESET';
export const REQUEST_START = 'REQUEST_START'
export const REQUEST_ERROR = 'REQUEST_ERROR'
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS'

export const SET_PAGINATION_DATA = 'SET_PAGINATION_DATA';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export const ADD_TO_CART = 'ADD_TO_CART';

// Homepage actions
export const FETCH_HOME_MENU = 'FETCH_HOME_MENU'
export const FETCH_HOME_MENU_SUCCESS = 'FETCH_HOME_MENU_SUCCESS'
export const FETCH_HOME_MENU_ERROR = 'FETCH_HOME_MENU_ERROR'
export const FETCH_HOME_MENU_RESET = 'FETCH_HOME_MENU_RESET'

export const SET_SLIDER_LISTS = 'SET_SLIDER_LISTS';
export const SET_BUSINESS_TYPE = 'SET_BUSINESS_TYPE';

// Cart actions
export const FETCH_CART_ITEMS = 'FETCH_CART_ITEMS'
export const FETCH_CART_ITEMS_SUCCESS = 'FETCH_CART_ITEMS_SUCCESS'
export const FETCH_CART_ITEMS_ERROR = 'FETCH_CART_ITEMS_ERROR'
export const FETCH_CART_ITEMS_RESET = 'FETCH_CART_ITEMS_RESET'

export const SET_CART_STATE = 'SET_CART_STATE'
export const ADD_TO_CART_START = 'ADD_TO_CART_START'
export const ADD_TO_CART_RESET = 'ADD_TO_CART_RESET'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'

export const REMOVE_SELECTED_FROM_CART_START = 'REMOVE_SELECTED_FROM_CART_START'
export const REMOVE_SELECTED_FROM_CART_RESET = 'REMOVE_SELECTED_FROM_CART_RESET'
export const REMOVE_SELECTED_FROM_CART = 'REMOVE_SELECTED_FROM_CART'

// Notification
export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';

//Checkout
export const SET_USER_DATA = 'SET_USER_DATA'
export const SET_STORE_ID = 'SET_STORE_ID'
export const SET_BILLING_ADDRESS_ID = 'SET_BILLING_ADDRESS_ID'
export const SET_SHIPPING_ADDRESS_ID = 'SET_SHIPPING_ADDRESS_ID'
export const SET_SHIPPING_INFO = 'SET_SHIPPING_INFO'
export const SET_SHIPPING_METHOD = 'SET_SHIPPING_METHOD'
export const SET_PAYMENT_INFO = 'SET_PAYMENT_INFO'
export const ADD_TO_COMPLETED = 'ADD_TO_COMPLETED'
export const SET_ACTIVE_STEP = 'SET_ACTIVE_STEP'
export const SET_NEW_ADDRESS = 'SET_NEW_ADDRESS'

//Auth Reducer
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const SET_VALID_AGE = 'SET_VALID_AGE'
export const SET_SHOW_LOGIN = 'SET_SHOW_LOGIN'
