export const data = [
  {
      "id": 1,
      "sku": null,
      "productName": "iPhone 7 Plus Front Camera Flex Cable with Proximity Sensor (Premium)",
      "alias": "OLED ASSEMBLY COMPATIBLE FOR IPHONE 11 PRO MAX (PREMIUM QUALITY, REFURBISHED) ",
      "availableQuantity": 84,
      "imageUrl": "https://neocellularparts.com/pub/media/catalog/product/cache/e1d8e380d449e6fe382fdbb8e9dd3f02/g/x/gx_hard_oled.png",
      "masterProductId": null,
      "taxClass": null,
      "standardPrice": 300.99,
      "tier1Price": 200.99,
      "tier2Price": 300.99,
      "tier3Price": 249.89,
      "tier4Price": 300.99,
      "tier5Price": 300.99,
      "tags": [
          "Featured Product",
          "New Product",
          "On Sale"
      ],
      "promotionType": null,
      "promotionValue": 0.0,
      "promotionStartdate": null,
      "promotionEnddate": null,
      "promotionNotes": null,
      "weight": null,
      "height": null,
      "length": null,
      "width": null
  },
  {
      "id": 2,
      "sku": null,
      "productName": "iPhone 7 Plus Back Housing with Small Parts Pre-installed (Matte Black)",
      "alias": "DIGITIZER COMPATIBLE FOR IPHONE 11 PRO MAX (PREMIUM QUALITY) (GLASS SEPARATION REQUIRED) (SOLDERING REQUIRED)",
      "availableQuantity": 15,
      "imageUrl": "https://neocellularparts.com/pub/media/catalog/product/cache/e1d8e380d449e6fe382fdbb8e9dd3f02/m/x/mx_-_black.png",
      "masterProductId": null,
      "taxClass": null,
      "standardPrice": 300.99,
      "tier1Price": 200.99,
      "tier2Price": 300.99,
      "tier3Price": 249.89,
      "tier4Price": 300.99,
      "tier5Price": 300.99,
      "tags": null,
      "promotionType": null,
      "promotionValue": 0.0,
      "promotionStartdate": null,
      "promotionEnddate": null,
      "promotionNotes": null,
      "weight": null,
      "height": null,
      "length": null,
      "width": null
  },
  {
      "id": 3,
      "sku": null,
      "productName": "iPhone 11 Pro Max OLED Assembly Premium Quality",
      "alias": "iPhone 11 Pro Max OLED Assembly Premium Quality",
      "availableQuantity": 0,
      "imageUrl": "https://neocellularparts.com/pub/media/catalog/product/cache/e1d8e380d449e6fe382fdbb8e9dd3f02/m/x/mx_-_black.png",
      "masterProductId": null,
      "taxClass": null,
      "standardPrice": 100.99,
      "tier1Price": 500.99,
      "tier2Price": 300.99,
      "tier3Price": 149.89,
      "tier4Price": 300.99,
      "tier5Price": 300.99,
      "tags": null,
      "promotionType": null,
      "promotionValue": 0.0,
      "promotionStartdate": null,
      "promotionEnddate": null,
      "promotionNotes": null,
      "weight": null,
      "height": null,
      "length": null,
      "width": null
  },
  {
      "id": 4,
      "sku": null,
      "productName": "iPhone XS Max 0.33mm 2.5D Premium Tempered Glass Screen Protector (Clear)",
      "alias": "iPhone XS Max 0.33mm 2.5D Premium Tempered Glass Screen Protector (Clear)",
      "availableQuantity": 30,
      "imageUrl": "https://neocellularparts.com/pub/media/catalog/product/cache/e1d8e380d449e6fe382fdbb8e9dd3f02/x/-/x-box.png",
      "masterProductId": null,
      "taxClass": null,
      "standardPrice": 200.99,
      "tier1Price": 300.99,
      "tier2Price": 300.99,
      "tier3Price": 249.89,
      "tier4Price": 300.99,
      "tier5Price": 300.99,
      "tags": null,
      "promotionType": null,
      "promotionValue": 0.0,
      "promotionStartdate": null,
      "promotionEnddate": null,
      "promotionNotes": null,
      "weight": null,
      "height": null,
      "length": null,
      "width": null
  },
  {
      "id": 5,
      "sku": null,
      "productName": "iPhone X Hard OLED Assembly (GX)",
      "alias": "iPhone X Hard OLED Assembly (GX)",
      "availableQuantity": -36,
      "imageUrl": "https://neocellularparts.com/pub/media/catalog/product/cache/e1d8e380d449e6fe382fdbb8e9dd3f02/1/0/100000001189.jpg",
      "masterProductId": null,
      "taxClass": null,
      "standardPrice": 300.99,
      "tier1Price": 100.99,
      "tier2Price": 300.99,
      "tier3Price": 349.89,
      "tier4Price": 300.99,
      "tier5Price": 300.99,
      "tags": [
          "Best Seller",
          "Featured Product",
          "New Product"
      ],
      "promotionType": null,
      "promotionValue": 0.0,
      "promotionStartdate": null,
      "promotionEnddate": null,
      "promotionNotes": null,
      "weight": null,
      "height": null,
      "length": null,
      "width": null
  },
  {
      "id": 6,
      "sku": null,
      "productName": "iPhone X/XS 0.33mm 2.5D Premium Tempered Glass Screen Protector (Clear)",
      "alias": "iPhone X/XS 0.33mm 2.5D Premium Tempered Glass Screen Protector (Clear)",
      "availableQuantity": 58,
      "imageUrl": "https://neocellularparts.com/pub/media/catalog/product/cache/e1d8e380d449e6fe382fdbb8e9dd3f02/f/r/front-camera-x.jpg",
      "masterProductId": null,
      "taxClass": null,
      "standardPrice": 400.99,
      "tier1Price": 700.99,
      "tier2Price": 300.99,
      "tier3Price": 449.89,
      "tier4Price": 300.99,
      "tier5Price": 300.99,
      "tags": null,
      "promotionType": null,
      "promotionValue": 0.0,
      "promotionStartdate": null,
      "promotionEnddate": null,
      "promotionNotes": null,
      "weight": null,
      "height": null,
      "length": null,
      "width": null
  },
  {
      "id": 7,
      "sku": null,
      "productName": "iPhone X/XS 0.3mm 2.5D Tempered Glass Screen Protector (Clear)",
      "alias": "iPhone X/XS 0.3mm 2.5D Tempered Glass Screen Protector (Clear)",
      "availableQuantity": 3696,
      "imageUrl": "https://neocellularparts.com/pub/media/catalog/product/cache/e1d8e380d449e6fe382fdbb8e9dd3f02/7/p/7pnv6w.png",
      "masterProductId": null,
      "taxClass": null,
      "standardPrice": 500.99,
      "tier1Price": 200.99,
      "tier2Price": 300.99,
      "tier3Price": 549.89,
      "tier4Price": 300.99,
      "tier5Price": 300.99,
      "tags": null,
      "promotionType": null,
      "promotionValue": 0.0,
      "promotionStartdate": null,
      "promotionEnddate": null,
      "promotionNotes": null,
      "weight": null,
      "height": null,
      "length": null,
      "width": null
  },
  {
      "id": 10,
      "sku": null,
      "productName": "QianLi iCopy Plus Programmer Tool with Battery Board",
      "alias": "QianLi iCopy Plus Programmer Tool with Battery Board",
      "availableQuantity": 238,
      "imageUrl": "https://neocellularparts.com/pub/media/catalog/product/cache/e1d8e380d449e6fe382fdbb8e9dd3f02/7/-/7-charging-port-white-am_1.png",
      "masterProductId": null,
      "taxClass": null,
      "standardPrice": 200.99,
      "tier1Price": 500.99,
      "tier2Price": 300.99,
      "tier3Price": 149.89,
      "tier4Price": 300.99,
      "tier5Price": 300.99,
      "tags": [
          "Featured Product",
          "New Product",
          "On Sale"
      ],
      "promotionType": null,
      "promotionValue": 0.0,
      "promotionStartdate": null,
      "promotionEnddate": null,
      "promotionNotes": null,
      "weight": null,
      "height": null,
      "length": null,
      "width": null
  },
  {
      "id": 11,
      "sku": null,
      "productName": "ZIZO BOLT Cover w/ Kickstand, Holster and Tempered Glass for iPhone 6/7/8 (Red/Black)",
      "alias": "ZIZO BOLT Cover w/ Kickstand, Holster and Tempered Glass for iPhone 6/7/8 (Red/Black)",
      "availableQuantity": 6,
      "imageUrl": "https://neocellularparts.com/pub/media/catalog/product/cache/e1d8e380d449e6fe382fdbb8e9dd3f02/7/-/7-plus-front-camera.png",
      "masterProductId": null,
      "taxClass": null,
      "standardPrice": 300.99,
      "tier1Price": 700.99,
      "tier2Price": 300.99,
      "tier3Price": 349.89,
      "tier4Price": 300.99,
      "tier5Price": 300.99,
      "tags": null,
      "promotionType": null,
      "promotionValue": 0.0,
      "promotionStartdate": null,
      "promotionEnddate": null,
      "promotionNotes": null,
      "weight": null,
      "height": null,
      "length": null,
      "width": null
  },
  {
      "id": 12,
      "sku": null,
      "productName": "ZIZO BOLT Cover w/ Kickstand, Holster and Tempered Glass for iPhone 6/7/8 (Desert Tan/Camo Green)",
      "alias": "ZIZO BOLT Cover w/ Kickstand, Holster and Tempered Glass for iPhone 6/7/8 (Desert Tan/Camo Green)",
      "availableQuantity": 63,
      "imageUrl": "https://neocellularparts.com/pub/media/catalog/product/cache/e1d8e380d449e6fe382fdbb8e9dd3f02/i/p/iphone-7-sim-tray-_red_.png",
      "masterProductId": null,
      "taxClass": null,
      "standardPrice": 400.99,
      "tier1Price": 300.99,
      "tier2Price": 300.99,
      "tier3Price": 549.89,
      "tier4Price": 300.99,
      "tier5Price": 300.99,
      "tags": null,
      "promotionType": null,
      "promotionValue": 0.0,
      "promotionStartdate": null,
      "promotionEnddate": null,
      "promotionNotes": null,
      "weight": null,
      "height": null,
      "length": null,
      "width": null
  },
  {
      "id": 13,
      "sku": null,
      "productName": "ZIZO BOLT Cover w/ Kickstand, Holster and Tempered Glass for iPhone 6/7/8 (Desert Tan/Camo Green)",
      "alias": "test",
      "availableQuantity": 32,
      "imageUrl": "https://neocellularparts.com/pub/media/catalog/product/cache/e1d8e380d449e6fe382fdbb8e9dd3f02/i/P/iPhone-7p-Back-red.gif",
      "masterProductId": null,
      "taxClass": null,
      "standardPrice": 500.99,
      "tier1Price": 100.99,
      "tier2Price": 300.99,
      "tier3Price": 149.89,
      "tier4Price": 300.99,
      "tier5Price": 300.99,
      "tags": null,
      "promotionType": null,
      "promotionValue": 0.0,
      "promotionStartdate": null,
      "promotionEnddate": null,
      "promotionNotes": null,
      "weight": null,
      "height": null,
      "length": null,
      "width": null
  },
  {
      "id": 14,
      "sku": null,
      "productName": "GHOSTEK CLOAK 4 FOR APPLE IPHONE XR (BLACK)",
      "alias": "GHOSTEK CLOAK 4 FOR APPLE IPHONE XR (BLACK)",
      "availableQuantity": 5,
      "imageUrl": null,
      "masterProductId": null,
      "taxClass": null,
      "standardPrice": 600.99,
      "tier1Price": 400.99,
      "tier2Price": 300.99,
      "tier3Price": 549.89,
      "tier4Price": 300.99,
      "tier5Price": 300.99,
      "tags": null,
      "promotionType": null,
      "promotionValue": 0.0,
      "promotionStartdate": null,
      "promotionEnddate": null,
      "promotionNotes": null,
      "weight": null,
      "height": null,
      "length": null,
      "width": null
  },
  {
      "id": 15,
      "sku": null,
      "productName": "GHOSTEK COVERT 2 FOR APPLE IPHONE XR (BLACK)",
      "alias": "GHOSTEK COVERT 2 FOR APPLE IPHONE XR (BLACK)",
      "availableQuantity": 0,
      "imageUrl": null,
      "masterProductId": null,
      "taxClass": null,
      "standardPrice": 700.99,
      "tier1Price": 300.99,
      "tier2Price": 300.99,
      "tier3Price": 149.89,
      "tier4Price": 300.99,
      "tier5Price": 300.99,
      "tags": null,
      "promotionType": null,
      "promotionValue": 0.0,
      "promotionStartdate": null,
      "promotionEnddate": null,
      "promotionNotes": null,
      "weight": null,
      "height": null,
      "length": null,
      "width": null
  },
  {
      "id": 16,
      "sku": null,
      "productName": "ZIZO BOLT Cover w/ Holster, Kickstand, Tempered Glass Screen Protector for iPhone 7P/8P (Black/Red)",
      "alias": "ZIZO BOLT Cover w/ Holster, Kickstand, Tempered Glass Screen Protector for iPhone 7P/8P (Black/Red)",
      "availableQuantity": 10,
      "imageUrl": null,
      "masterProductId": null,
      "taxClass": null,
      "standardPrice": 300.99,
      "tier1Price": 200.99,
      "tier2Price": 300.99,
      "tier3Price": 249.89,
      "tier4Price": 300.99,
      "tier5Price": 300.99,
      "tags": null,
      "promotionType": null,
      "promotionValue": 0.0,
      "promotionStartdate": null,
      "promotionEnddate": null,
      "promotionNotes": null,
      "weight": null,
      "height": null,
      "length": null,
      "width": null
  },
  {
      "id": 17,
      "sku": null,
      "productName": "ZIZO BOLT Cover w/ Holster, Kickstand, Tempered Glass Screen Protector for iPhone 7P/8P (Black/Black)",
      "alias": "ZIZO BOLT Cover w/ Holster, Kickstand, Tempered Glass Screen Protector for iPhone 7P/8P (Black/Black)",
      "availableQuantity": -12,
      "imageUrl": null,
      "masterProductId": null,
      "taxClass": null,
      "standardPrice": 300.99,
      "tier1Price": 200.99,
      "tier2Price": 300.99,
      "tier3Price": 249.89,
      "tier4Price": 300.99,
      "tier5Price": 300.99,
      "tags": null,
      "promotionType": null,
      "promotionValue": 0.0,
      "promotionStartdate": null,
      "promotionEnddate": null,
      "promotionNotes": null,
      "weight": null,
      "height": null,
      "length": null,
      "width": null
  },
  {
      "id": 18,
      "sku": null,
      "productName": "ZIZO BOLT Cover w/ Holster, Kickstand, Tempered Glass Screen Protector for iPhone 7P/8P (Black/Black)",
      "alias": "ZIZO BOLT Cover w/ Holster, Kickstand, Tempered Glass Screen Protector for iPhone 7P/8P (Black/Black)",
      "availableQuantity": 23,
      "imageUrl": null,
      "masterProductId": null,
      "taxClass": null,
      "standardPrice": 300.99,
      "tier1Price": 200.99,
      "tier2Price": 300.99,
      "tier3Price": 249.89,
      "tier4Price": 300.99,
      "tier5Price": 300.99,
      "tags": null,
      "promotionType": null,
      "promotionValue": 0.0,
      "promotionStartdate": null,
      "promotionEnddate": null,
      "promotionNotes": null,
      "weight": null,
      "height": null,
      "length": null,
      "width": null
  },
  {
      "id": 20,
      "sku": null,
      "productName": "Mater Product Test",
      "alias": "Mater Product Test-1",
      "availableQuantity": null,
      "imageUrl": null,
      "masterProductId": null,
      "taxClass": null,
      "standardPrice": 12.00,
      "tier1Price": 12.00,
      "tier2Price": 12.00,
      "tier3Price": 12.00,
      "tier4Price": 12.00,
      "tier5Price": 12.00,
      "tags": null,
      "promotionType": null,
      "promotionValue": 0.0,
      "promotionStartdate": null,
      "promotionEnddate": null,
      "promotionNotes": null,
      "weight": null,
      "height": null,
      "length": null,
      "width": null
  },
  {
      "id": 21,
      "sku": null,
      "productName": "Mater Product Test",
      "alias": "Mater Product Test-2",
      "availableQuantity": null,
      "imageUrl": null,
      "masterProductId": null,
      "taxClass": null,
      "standardPrice": 12.00,
      "tier1Price": 12.00,
      "tier2Price": 12.00,
      "tier3Price": 12.00,
      "tier4Price": 12.00,
      "tier5Price": 12.00,
      "tags": null,
      "promotionType": null,
      "promotionValue": 0.0,
      "promotionStartdate": null,
      "promotionEnddate": null,
      "promotionNotes": null,
      "weight": null,
      "height": null,
      "length": null,
      "width": null
  },
  {
      "id": 22,
      "sku": null,
      "productName": "Mater Product Test",
      "alias": "Mater Product Test-3",
      "availableQuantity": null,
      "imageUrl": null,
      "masterProductId": null,
      "taxClass": null,
      "standardPrice": 12.00,
      "tier1Price": 12.00,
      "tier2Price": 12.00,
      "tier3Price": 12.00,
      "tier4Price": 12.00,
      "tier5Price": 12.00,
      "tags": null,
      "promotionType": null,
      "promotionValue": 0.0,
      "promotionStartdate": null,
      "promotionEnddate": null,
      "promotionNotes": null,
      "weight": null,
      "height": null,
      "length": null,
      "width": null
  },
  {
      "id": 23,
      "sku": null,
      "productName": "Mater Product Test",
      "alias": "Mater Product Test-4",
      "availableQuantity": null,
      "imageUrl": null,
      "masterProductId": null,
      "taxClass": null,
      "standardPrice": 12.00,
      "tier1Price": 12.00,
      "tier2Price": 12.00,
      "tier3Price": 12.00,
      "tier4Price": 12.00,
      "tier5Price": 12.00,
      "tags": null,
      "promotionType": null,
      "promotionValue": 0.0,
      "promotionStartdate": null,
      "promotionEnddate": null,
      "promotionNotes": null,
      "weight": null,
      "height": null,
      "length": null,
      "width": null
  }
]

export const productsData = [{
  "id": "1",
  "SKU": "21234",
  "productShortDescription": "OLED Assembly Compatible For iPhone 11 Pro (Aftermarket Plus Quality, GX / Soft)",
  "productFullDescription": "",
  "price": 690,
  "images": [{ "url": "https://media.mobilesentrix.com/catalog/product/cache/1/image/272x360/9df78eab33525d08d6e5fb8d27136e95/1/1/11pro.png", "sequenceNumber": 1 }],
  "productVariants": [],
  "relatedProducts": [],
  "availabeQuantity": 100,
  "maxPurchaseAllowed": 50,
  "mainProductImage": "https://media.mobilesentrix.com/catalog/product/cache/1/image/272x360/9df78eab33525d08d6e5fb8d27136e95/1/1/11pro.png",
},
{
  "id": "2",
  "SKU": "21234",
  "productShortDescription": "Replacement Battery Compatible For iPhone 11 Pro (AmpSentrix)",
  "productFullDescription": "",
  "price": 4500,
  "images": [{ "url": "https://media.mobilesentrix.com/catalog/product/cache/1/small_image/210x/0dc2d03fe217f8c83829496872af24a0/1/1/11pro.png", "sequenceNumber": 1 }],
  "productVariants": [],
  "relatedProducts": [],
  "availabeQuantity": 40,
  "maxPurchaseAllowed": 10,
  "mainProductImage": "https://media.mobilesentrix.com/catalog/product/cache/1/small_image/210x/0dc2d03fe217f8c83829496872af24a0/1/1/11pro.png",
},
{
  "id": "3",
  "SKU": "21234",
  "productShortDescription": "Back Camera Lens (Glass Only) with Adhesive Tape Compatible For iPhone 11 Pro / Pro Max (3 Piece Set) (10 Pack) (Real Sapphire / Premium Quality)Back Camera Lens (Glass Only) with Adhesive",
  "productFullDescription": "",
  "price": 870,
  "images": [{ "url": "", "sequenceNumber": 1 }],
  "productVariants": [],
  "relatedProducts": [],
  "availabeQuantity": 19,
  "maxPurchaseAllowed": 6,
  "mainProductImage": "https://media.mobilesentrix.com/catalog/product/cache/1/small_image/210x/0dc2d03fe217f8c83829496872af24a0/1/0/107082069332-a_1_1.jpg",
},
{
  "id": "4",
  "SKU": "21234",
  "productShortDescription": "OLED Assembly Compatible For iPhone 11 Pro (Aftermarket Plus Quality, GX / Soft)",
  "productFullDescription": "",
  "price": 690,
  "images": [{ "url": "https://media.mobilesentrix.com/catalog/product/cache/1/image/272x360/9df78eab33525d08d6e5fb8d27136e95/1/1/11pro.png", "sequenceNumber": 1 }],
  "productVariants": [],
  "relatedProducts": [],
  "availabeQuantity": 0,
  "maxPurchaseAllowed": 50,
  "mainProductImage": "https://media.mobilesentrix.com/catalog/product/cache/1/image/272x360/9df78eab33525d08d6e5fb8d27136e95/1/1/11pro.png",
},
{
  "id": "5",
  "SKU": "21234",
  "productShortDescription": "Replacement Battery Compatible For iPhone 11 Pro (AmpSentrix)",
  "productFullDescription": "",
  "price": 4500,
  "images": [{ "url": "https://media.mobilesentrix.com/catalog/product/cache/1/small_image/210x/0dc2d03fe217f8c83829496872af24a0/1/1/11pro.png", "sequenceNumber": 1 }],
  "productVariants": [],
  "relatedProducts": [],
  "availabeQuantity": 40,
  "maxPurchaseAllowed": 10,
  "mainProductImage": "https://media.mobilesentrix.com/catalog/product/cache/1/small_image/210x/0dc2d03fe217f8c83829496872af24a0/1/1/11pro.png",
},
{
  "id": "6",
  "SKU": "21234",
  "productShortDescription": "Back Camera Lens (Glass Only) with Adhesive Tape Compatible For iPhone 11 Pro / Pro Max (3 Piece Set) (10 Pack) (Real Sapphire / Premium Quality)",
  "productFullDescription": "",
  "price": 870,
  "images": [{ "url": "", "sequenceNumber": 1 }],
  "productVariants": [],
  "relatedProducts": [],
  "availabeQuantity": 0,
  "maxPurchaseAllowed": 6,
  "mainProductImage": "https://media.mobilesentrix.com/catalog/product/cache/1/small_image/210x/0dc2d03fe217f8c83829496872af24a0/1/0/107082069332-a_1_1.jpg",
},
{
  "id": "7",
  "SKU": "21234",
  "productShortDescription": "OLED Assembly Compatible For iPhone 11 Pro (Aftermarket Plus Quality, GX / Soft)",
  "productFullDescription": "",
  "price": 690,
  "images": [{ "url": "https://media.mobilesentrix.com/catalog/product/cache/1/image/272x360/9df78eab33525d08d6e5fb8d27136e95/1/1/11pro.png", "sequenceNumber": 1 }],
  "productVariants": [],
  "relatedProducts": [],
  "availabeQuantity": 100,
  "maxPurchaseAllowed": 50,
  "mainProductImage": "https://media.mobilesentrix.com/catalog/product/cache/1/image/272x360/9df78eab33525d08d6e5fb8d27136e95/1/1/11pro.png",
},
{
  "id": "8",
  "SKU": "21234",
  "productShortDescription": "Replacement Battery Compatible For iPhone 11 Pro (AmpSentrix)",
  "productFullDescription": "",
  "price": 4500,
  "images": [{ "url": "https://media.mobilesentrix.com/catalog/product/cache/1/small_image/210x/0dc2d03fe217f8c83829496872af24a0/1/1/11pro.png", "sequenceNumber": 1 }],
  "productVariants": [],
  "relatedProducts": [],
  "availabeQuantity": 40,
  "maxPurchaseAllowed": 10,
  "mainProductImage": "https://media.mobilesentrix.com/catalog/product/cache/1/small_image/210x/0dc2d03fe217f8c83829496872af24a0/1/1/11pro.png",
},
{
  "id": "9",
  "SKU": "21234",
  "productShortDescription": "Back Camera Lens (Glass Only) with Adhesive Tape Compatible For iPhone 11 Pro / Pro Max (3 Piece Set) (10 Pack) (Real Sapphire / Premium Quality)",
  "productFullDescription": "",
  "price": 870,
  "images": [{ "url": "", "sequenceNumber": 1 }],
  "productVariants": [],
  "relatedProducts": [],
  "availabeQuantity": 19,
  "maxPurchaseAllowed": 6,
  "mainProductImage": "https://media.mobilesentrix.com/catalog/product/cache/1/small_image/210x/0dc2d03fe217f8c83829496872af24a0/1/0/107082069332-a_1_1.jpg",
},
{
  "id": "10",
  "SKU": "21234",
  "productShortDescription": "OLED Assembly Compatible For iPhone 11 Pro (Aftermarket Plus Quality, GX / Soft)",
  "productFullDescription": "",
  "price": 690,
  "images": [{ "url": "https://media.mobilesentrix.com/catalog/product/cache/1/image/272x360/9df78eab33525d08d6e5fb8d27136e95/1/1/11pro.png", "sequenceNumber": 1 }],
  "productVariants": [],
  "relatedProducts": [],
  "availabeQuantity": 100,
  "maxPurchaseAllowed": 50,
  "mainProductImage": "https://media.mobilesentrix.com/catalog/product/cache/1/image/272x360/9df78eab33525d08d6e5fb8d27136e95/1/1/11pro.png",
},
{
  "id": "11",
  "SKU": "21234",
  "productShortDescription": "Replacement Battery Compatible For iPhone 11 Pro (AmpSentrix)",
  "productFullDescription": "",
  "price": 4500,
  "images": [{ "url": "https://media.mobilesentrix.com/catalog/product/cache/1/small_image/210x/0dc2d03fe217f8c83829496872af24a0/1/1/11pro.png", "sequenceNumber": 1 }],
  "productVariants": [],
  "relatedProducts": [],
  "availabeQuantity": 0,
  "maxPurchaseAllowed": 10,
  "mainProductImage": "https://media.mobilesentrix.com/catalog/product/cache/1/small_image/210x/0dc2d03fe217f8c83829496872af24a0/1/1/11pro.png",
},
{
  "id": "12",
  "SKU": "21234",
  "productShortDescription": "Back Camera Lens (Glass Only) with Adhesive Tape Compatible For iPhone 11 Pro / Pro Max (3 Piece Set) (10 Pack) (Real Sapphire / Premium Quality)",
  "productFullDescription": "",
  "price": 870,
  "images": [{ "url": "", "sequenceNumber": 1 }],
  "productVariants": [],
  "relatedProducts": [],
  "availabeQuantity": 19,
  "maxPurchaseAllowed": 6,
  "mainProductImage": "https://media.mobilesentrix.com/catalog/product/cache/1/small_image/210x/0dc2d03fe217f8c83829496872af24a0/1/0/107082069332-a_1_1.jpg",
},
{
  "id": "13",
  "SKU": "21234",
  "productShortDescription": "OLED Assembly Compatible For iPhone 11 Pro (Aftermarket Plus Quality, GX / Soft)",
  "productFullDescription": "",
  "price": 690,
  "images": [{ "url": "https://media.mobilesentrix.com/catalog/product/cache/1/image/272x360/9df78eab33525d08d6e5fb8d27136e95/1/1/11pro.png", "sequenceNumber": 1 }],
  "productVariants": [],
  "relatedProducts": [],
  "availabeQuantity": 100,
  "maxPurchaseAllowed": 50,
  "mainProductImage": "https://media.mobilesentrix.com/catalog/product/cache/1/image/272x360/9df78eab33525d08d6e5fb8d27136e95/1/1/11pro.png",
},
{
  "id": "14",
  "SKU": "21234",
  "productShortDescription": "Replacement Battery Compatible For iPhone 11 Pro (AmpSentrix)",
  "productFullDescription": "",
  "price": 4500,
  "images": [{ "url": "https://media.mobilesentrix.com/catalog/product/cache/1/small_image/210x/0dc2d03fe217f8c83829496872af24a0/1/1/11pro.png", "sequenceNumber": 1 }],
  "productVariants": [],
  "relatedProducts": [],
  "availabeQuantity": 40,
  "maxPurchaseAllowed": 10,
  "mainProductImage": "https://media.mobilesentrix.com/catalog/product/cache/1/small_image/210x/0dc2d03fe217f8c83829496872af24a0/1/1/11pro.png",
},
{
  "id": "15",
  "SKU": "21234",
  "productShortDescription": "Back Camera Lens (Glass Only) with Adhesive Tape Compatible For iPhone 11 Pro / Pro Max (3 Piece Set) (10 Pack) (Real Sapphire / Premium Quality)",
  "productFullDescription": "",
  "price": 870,
  "images": [{ "url": "", "sequenceNumber": 1 }],
  "productVariants": [],
  "relatedProducts": [],
  "availabeQuantity": 19,
  "maxPurchaseAllowed": 6,
  "mainProductImage": "https://media.mobilesentrix.com/catalog/product/cache/1/small_image/210x/0dc2d03fe217f8c83829496872af24a0/1/0/107082069332-a_1_1.jpg",
},

]

export const filterData = [
  {
    name: "Product Category",
    options: [
      {
        name: "Samsung",
        options: [
          "Samsung Galaxy",
          "Samsung X2",
          "Samsung J"
        ]
      },
      {
        name: "Apple",
        options: [
          "Iphone",
          "Iphone XR",
          "Iphone MAX"
        ]
      },
      {
        name: "Some Other",
        options: null
      },
    ]
  },
  {
    name: "Brands",
    options: [
      {
        name: "Samsung",
        options: [
          "Samsung Galaxy",
          "Samsung X2",
          "Samsung J"
        ]
      },
      {
        name: "Apple",
        options: [
          "Iphone",
          "Iphone XR",
          "Iphone MAX"
        ]
      },
      {
        name: "Some Other",
        options: null
      },
    ]
  },
  {
    name: "Flavour Profile",
    options: [
      {
        name: "Samsung",
        options: [
          "Samsung Galaxy",
          "Samsung X2",
          "Samsung J"
        ]
      },
      {
        name: "Apple",
        options: [
          "Iphone",
          "Iphone XR",
          "Iphone MAX"
        ]
      },
      {
        name: "Some Other",
        options: null
      },
    ]
  },
]